apiVersion: batch/v1
kind: Job
metadata:
  name: postgres-init
  namespace: betteruptime
spec:
  template:
    spec:
      restartPolicy: OnFailure
      initContainers:
        - name: wait-for-postgres
          image: aabhii/betteruptime-init:amd64-latest
          command: ["/app/wait-for-postgres.sh", "postgres", "5432", "postgres"]

      containers:
        - name: postgres-init
          image: aabhii/betteruptime-init:amd64-latest
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: DATABASE_URL
          command: ["/app/postgres-init.sh"]