apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: betteruptime
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          image: aabhii/betteruptime-worker:amd64-latest
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: DATABASE_URL

            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: redis-secret
                  key: REDIS_URL
                  
            - name: REGION_ID_USA
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: REGION_ID_USA
            - name: REGION_NAME_USA
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: REGION_NAME_USA

            - name: REGION_ID_INDIA
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: REGION_ID_INDIA
            - name: REGION_NAME_INDIA
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: REGION_NAME_INDIA

            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: POSTGRES_HOST

            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: POSTGRES_USER

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: POSTGRES_PASSWORD
      restartPolicy: Always